version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/node_modules # https://castaneai.hatenablog.com/entry/2019/01/29/151257
    depends_on:
      - prisma-db
      - prisma-test-db
  prisma-db:
    container_name: prisma-db
    image: postgres:12
    ports:
      - '5403:5432'
    volumes:
      - prisma-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
  prisma-test-db:
    container_name: prisma-test-db
    image: postgres:12
    ports:
      - '5402:5432'
    volumes:
      - prisma-test-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'

volumes:
  prisma-store:
    driver: local
  prisma-test-store:
    driver: local
