name: After Actions

on:
  workflow_run:
    workflows:
      - Main
    branches: settings-ci
    types:
      - 'completed'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
