name: After Actions

on:
  pull_request:
    types: [opened, edited]
    branches:
      - "test/**"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github.event.pull_request.html_url) }}'
