name: release-pr
on:
  push
  # schedule:
  #   - cron: '*/5 * * * *'
  #   branches:
  #     - test
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
        # - name: Create a release branch
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   run: |
        #     git switch -c test
        #     git push origin test
      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: test
        run: |
          gem install -N git-pr-release
          git-pr-release
      - name: Get PR
        run: |
          pr_url(gh pr list --head test --json 'url' --jq '.[].url')
          echo $pr_url
      # - name: Save PR number
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     mkdir -p ./pr
      #     echo $PR_NUMBER > ./pr/pr_number
      #
