name: Lint

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install npm
        run: yarn install
      - name: Lint
        run: yarn run lint
