name: Lint

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: prisma2020
          POSTGRES_DB: prisma
          POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
          TZ: 'Asia/Tokyo'
        ports:
          - '5402:5432'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 15.5
        uses: actions/setup-node@v2
        with:
          node-version: 15.5.0
          cache: npm

      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Setup Test DB
        run: >
          npm run migrate:test
          npm run model-generate
      - name: Test Integration
        run: npm run test:integration
